### ISSUE TITLE
EPIC- As a Computer Science student, I want to see video tutorials/examples so that I can better understand the concepts being presented.

### ISSUE THREAD

**Issue by MathewLie** [CEN3031-5c/sapphire-project18-5cv2#1]
**Acceptance Criteria:**
- [ ] User is provided with video interface
- [ ] User is allowed to move within timestamps
- [ ] User is allowed to interact with video
- [ ] Videos should play smoothly on different devices.
- [ ] Interactive elements should be functional and record student's input.

**Tasks:**
- [ ] Break this epic into smaller user stories.
