### ISSUE TITLE
As a teacher, I would like to keep my academic plans more organized by being able to delete old lessons and any videos associated with them.

### ISSUE THREAD

**Issue by MathewLie** [CEN3031-5c/sapphire-project18-5cv2#3]
**Acceptance Criteria:** 
- [ ] Create a teacher lesson plan dashboard
- [x] Create a delete option
- [ ] Delete option should remove lessons and associated videos

**Tasks:**

_Sprint 1_
- [ ] On lesson deletion, delete corresponding video ids[1]
- [x] Option to remove video in lesson[1]
- [ ] Allow creators to remove videos from the gallery if they posted them.[1] 
- [ ] Delete video ids from db if they aren't being used in lesson, gallery, or workspace[1]

_Sprint 2_
- [ ] On lesson deletion, delete corresponding video ids[3]
- [x] Querying with backend [4]
- [x] Allow creators to remove videos from the gallery if they posted them.[3]
- [ ] Set up automatic deletion after certain time to save space [4]
- [x] Edit general styling and CSS of delete / popup functionalities [1]
