### ISSUE TITLE
As a video uploader, I want to store videos in a database with the data stored within creator id, name, video id, inGallery, inLesson, inWorkspace.

### ISSUE THREAD

**Issue by MathewLie** [CEN3031-5c/sapphire-project18-5cv2#4]
**Acceptance Criteria:**

- [x] Must have video able to be uploaded.
- [x] Video must have data types filled.
- [x] Video must be allowed to be placed in Gallery, Lesson, Workspace etc.

**Tasks:**

_Sprint 1_
- [x] Make SQL table to hold video ids (Should be tied to content creators)[1]
- [x] Store creator id, name, video id, inGallery, inLesson, inWorkspace[1]
- [x] Test querying to the CASMM Collection[1]

_Sprint 2_

- [x] Connect the backend with API
- [x] Create official CASMM Collection vs. dummy and test functionality between both [3]

**Comment by MathewLie** [comment]
**UPDATE**

Edited CASMM Collection to have new criteria and fields for each frontend feature. These include:

- name
- UID
- URL
- InGallery
- inWorkspace
- inLesson
- teacherQuestion
- creatorID

Wrote queries and they are connected with frontend

**Comment by MathewLie** [comment]
Test
